[pytest]
filterwarnings =
    ignore:Type google._upb._message.MessageMapContainer:DeprecationWarning
    ignore:Type google._upb._message.ScalarMapContainer:DeprecationWarning
    ignore:SymbolDatabase.GetSymbol:UserWarning
